### ISSUE TITLE
Not working in a background job

### ISSUE THREAD

**Issue by ben-gy** [ankane/lockbox#126] opened 2021-06-06 01:17 UTC
Hey @ankane - thanks for this gem. It's filled a big hole in the Rails framework to date.

I've run into a strange issue that I can't explain and was hoping you could shed some light on what I've done wrong here.

### Setup
* I'm running Sidekiq on Redis
* I've encrypted a field (full_name) in a model (ComplianceRecord)
* I'm sending the database ID (for the ComplianceRecord model instance) as a variable when spinning up the background job

### Problem
* I'm running the decrypt script in the readme to unencrypted the full_name field in the job (as it is outside the model)
* It is returning nil when it should be returning a string of text

### Code flow
1. Set the instance variable using the database id (@compliance_record)
```
@compliance_record = ComplianceRecord.find(compliance_record_id)
```
2. Un-encrypt the data and set to a @full_name variable
```
@full_name = ComplianceRecord.decrypt_full_name_ciphertext(@compliance_record.full_name_ciphertext)
```

### Debug steps

I put a byebug in after setting the variable to have a play around and here's what I found:
* ```ComplianceRecord.decrypt_full_name_ciphertext(@compliance_record.full_name_ciphertext)``` produces ```nil```
* ```ComplianceRecord.decrypt_full_name_ciphertext(ComplianceRecord.last.full_name_ciphertext)``` (```last``` is also the same record as ```@compliance_record``` produces a string with the full name in it e.g. ```"Ben Richardson"```
* ```ComplianceRecord.decrypt_full_name_ciphertext(ComplianceRecord.find(11).full_name_ciphertext)``` produces ```nil```

Can you help me understand why the first and third bullet points are producing a ```nil``` result?

Thanks in advance mate 😀

**Comment by jnylen** [comment] 2021-06-07 06:27
JFYI;
I'm having issues with Lockbox in ActiveJob as well. I did some inspect and it seems something is off when trying to decrypt or encrypt it somehow doesn't set the key.

I specifically pass in a key and it works fine if I do it in the console.

Seems to be an issue when using two decrypts in one job.

I.e. what I do is:

1. Encrypt an access token and a unique seperate token with the master key
2. Decrypt these
3. Pass the token along to a custom Rails Redis service (this one works outside of the jobs with the same calls)


The only thing that differ is step 1 and 2.

@ben-gy do you have something similar perhaps?

**Comment by ankane** [comment] 2021-06-09 06:59
@ben-gy `decrypt_#{attribute}_ciphertext` should only return `nil` if the input is `nil`, so I'm guessing that's the cause. If you're enqueuing the job in a database transaction, the job may be starting before the transaction is committed.

@jnylen I don't completely follow the issue you're seeing, but feel free to create a new issue with the code.

**Closed** 2021-06-30 17:47 UTC
